#   docker compose -f docker-compose.yml -f docker-compose-mac.yml up --build
services:
  postgres:
    platform: linux/arm64
  backend:
    platform: linux/arm64
  frontend:
    platform: linux/arm64
# hajcbhjabchjbdhjcbjsh